### ISSUE TITLE
سیستم ثبت نام

### ISSUE THREAD

**Issue by includeamin** [includeamin/RASTAN-WORD-GAME#1]
نام کاربری به همراه شماره موبایل یا ایمیل
که برای هر دو اعتبار سنجی نیاز است
در صورت وارد کردن ایمیل باید یک پسورد نیز بنویسد

**Comment by includeamin** [comment]
```
http://ip:3022/users/signup/gust/
response : {"State": true, "Description": "{\"UserName\": \"dc379e0a10b42f045d7d4ffb166ae3e4986ad53463062896dd60a8341e3d6eed\", \"Token\": \"041c48a0a1543bc974b2b7d706c15486f3df75c8430367440afe4c11263ac0a0\"}"}
```
```
http://ip:3022/users/signup/phone/
body ={PhoneNumber:xxx,UserName:xxx}
response:
success {"State": true, "Description": "User added and code sent"}
faild 
wrnig signup method {"State": true, "Description": "WSM"} 

Active account with code : 
http://ip:3022/users/account/active/phone/xxxx/yyy
xxx = user phonenumber
yyy = 4 digit code number
result 
success 
{"State": true, "Description": "token"}
```

```
signup with email
http://ip:3022/users/signup/email/
body ={UserName:xxx,Email:xxx,PassWord:xxx}
result : {"State": true, "Description": "CSE"}  CSE= code send to email
active account with email
http://ip:3022/users/account/active/email/xxx/yyy
xxx : email address
yyy: code
result 
success 
{"State": true, "Description": "token"}
```

**Comment by includeamin** [comment]
#login
```
http://ip:3022/users/login/phone/xxx/0
xxx : user phonenumber
0 : should always equal 0 when using phone method
code send to phonenumber and should using active account url to get token
Active account with code : 
http://ip:3022/users/account/active/phone/xxxx/yyy
xxx = user phonenumber
yyy = 4 digit code number
result 
success 
{"State": true, "Description": "token"}
```
```
http://ip:3022/users/login/email/xxx/yyy
xxx : user mail address
yyy : password
result
{"State": true, "Description": "token"}
```

**Comment by includeamin** [comment]
login as gust sample return value:
```
{
    "State": true,
    "Description": "{\"UserName\": \"\\u06a9\\u0627\\u0631\\u0628\\u0631\\u0645\\u0647\\u0645\\u0627\\u06464570\", \"Token\": \"d7f2c9266dd44ddf5e58e161e1cd1120fc78dac0aa7e58f7ee0c2053d484bf9b\", \"Id\": \"5c4d6e0495fb82000acf4e61\"}"
}
```
ghesmate Description UserName , Token , va Id karbaro mehman o mide bet
```
{
    "Id": "5c4d6ba3fe2bed048d6869dd",
    "Token": "ed3caeecbc467b38d19b4e2f91d45e68ba2799fe5c4f947e232149bea444d51d",
    "UserName": "کاربرمهمان7767"
}
```
ghesmate description encode shode nist chon farsie vaghti tabdil be reshte mishe in mishe agar serfan description o be json codo dobare username farsi mishe
@mohsen011

**Comment by includeamin** [comment]
bara sign up ba phonenumber ham mese dasture ghable fght tu body {OldUserName} ezafe mishe  k hamun id e hast k az karbare mehman dari UserName e k tu body e ghabli bud mishe UserName jadidesh

**Comment by includeamin** [comment]
baraie signup ba email ham mese ghable fght OldUserName be body ezafe mishe
ke hamun id e hast k tu meghdar bazgashtie

**Comment by mohsen011** [comment]
> #login
> @mohsen011
> 
> ```
> http://ip:3022/users/login/phone/xxx/0
> xxx : user phonenumber
> 0 : should always equal 0 when using phone method
> code send to phonenumber and should using active account url to get token
> Active account with code : 
> http://ip:3022/users/account/active/phone/xxxx/yyy
> xxx = user phonenumber
> yyy = 4 digit code number
> result 
> success 
> {"State": true, "Description": "token"}
> ```
> ```
> http://ip:3022/users/login/email/xxx/yyy
> xxx : user mail address
> yyy : password
> result
> {"State": true, "Description": "token"}
> ```

لاگیم با ایمیل بشود با یوزر نیم
