### ISSUE TITLE
سوالات و جواب های عمومی

### ISSUE THREAD

**Issue by mohsen011** [includeamin/RASTAN-WORD-GAME#2]
من فعلنه مواردی که بیشتر اهمیت داشت رو نوشتم.

**Comment by includeamin** [comment]
alie khaste nabashi

**Comment by includeamin** [comment]
config smtp server email o bede 
mamnun

**Comment by includeamin** [comment]
@mohsen011  config smtp server email o bede
mamnun

**Comment by includeamin** [comment]
@mohsen011 mohsen sakhtar inventory o behem bgu 
shamele

**Comment by mohsen011** [comment]
الان برات میفرستم

**Comment by mohsen011** [comment]
Eye:@EyeBro:@Cloth:@Gune:@Glass:@Nose:@Lips:@Hair:@
مقدار دیفالت اینه که هیچ ای دی ندارن
این برای ایتم های خریداری شده هست

**Comment by includeamin** [comment]
okaye man json mikonm inao formatesho behet migm k be ch surate

**Comment by mohsen011** [comment]
حله

**Comment by includeamin** [comment]
baraie active kardan account niaz hast k ip check beshe? ip un systemi k  bahash sabte nam shode va un systemi k bahash mikhad codo active kone?
masln man ba ip x.x.x.x signup kardam va mikhm ba ip x.x.x.y active konam accounto
inja barresi beshe k hatmn ip ha yeki bashan ya na? @mohsen011

**Comment by includeamin** [comment]
@mohsen011 baraie login ba hardo ravesh email phonenumber , username ejbari hast dg droste?

**Comment by mohsen011** [comment]
اره

**Comment by includeamin** [comment]
are mirese emruz @mohsen011

**Comment by mohsen011** [comment]
یه سوال نام کاربری تو چه فرمتی اینکریپت شده؟

**Comment by includeamin** [comment]
hash hast , name karbarie gust ke  encrypt nashode random generate shode  name karbari encrypt nmishe asan fght password encrypt mishe @mohsen011

**Comment by mohsen011** [comment]
من الان نیاز دارم برای نمایش این اینو دیکود کنم.ولی فرمت اش رو نمیدونم چیه

**Comment by mohsen011** [comment]
مثلا تو یه پروژه من تو فرمت base64 اینکود و دیکود میکردم
